<template>
    <v-container>
        <v-row justify="center" class="mx-15">
            <h1 class="display-2 font-weight-bold mb-3">Expension's privacy policy</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut porta ex fermentum tellus rhoncus interdum. Nunc interdum efficitur ante, quis tincidunt tortor interdum in. Pellentesque vel euismod erat. Curabitur fringilla ipsum mi, rhoncus sagittis nulla sagittis eu. Donec a cursus augue. Proin fermentum ex eget semper aliquam. Pellentesque efficitur in nisi et iaculis. Sed libero justo, aliquam at mattis nec, tristique at massa. Mauris porttitor aliquet risus, eget sollicitudin metus lacinia blandit. Maecenas nec velit dui. Nulla a orci luctus, efficitur massa et, eleifend eros. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla interdum consequat sapien et consequat. Donec nec erat odio. In eget est et ligula condimentum cursus faucibus a tellus.</p>
            <p>Morbi a dapibus orci, vel viverra nulla. Vivamus quis viverra urna. Proin dictum velit felis, sed eleifend justo ornare eu. Ut dignissim ipsum non mauris porttitor, sed cursus purus volutpat. Suspendisse sollicitudin tempus nisi, ut bibendum mi volutpat ut. Morbi efficitur lacinia libero eget suscipit. Sed bibendum molestie nisi. Nulla tempus nisi at lacus accumsan pellentesque. Cras sit amet bibendum quam.</p>
            <p>Quisque pulvinar convallis nibh. Proin erat lectus, posuere vitae velit sed, venenatis sollicitudin nibh. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer non nunc sit amet elit bibendum sagittis ac vel neque. Pellentesque a facilisis erat. Praesent sollicitudin ex id odio elementum, eget finibus metus sollicitudin. Suspendisse sit amet efficitur lacus. Proin eu feugiat diam. Proin tempus ultricies ullamcorper.</p>
            <p>Nulla vehicula, augue nec blandit posuere, nulla tellus tristique elit, ut dapibus arcu sapien efficitur turpis. Quisque ultricies eu risus sit amet maximus. Integer at tellus at purus interdum ullamcorper. Vestibulum interdum lorem metus, a fringilla libero hendrerit sit amet. Nulla finibus pretium ex in egestas. Maecenas erat enim, malesuada eget rhoncus in, scelerisque et elit. Nulla vel tellus id nisl accumsan molestie sit amet non justo. Mauris cursus, purus sit amet feugiat dapibus, massa odio molestie est, vitae feugiat mauris dui eu eros. Pellentesque efficitur vitae risus sit amet ornare. Donec in sodales nibh. In hac habitasse platea dictumst. Proin rhoncus tempor lacinia. Nullam iaculis finibus risus, at congue erat tempus in. Sed mauris urna, ullamcorper id nisl vel, vestibulum finibus urna. Nulla non aliquet enim. Aenean luctus, magna sit amet tempor fermentum, metus tortor euismod ligula, nec condimentum neque leo in odio.</p>
            <p>In eget placerat dolor, sed dictum dolor. Nunc sit amet quam ullamcorper, sagittis magna non, pretium orci. Quisque tincidunt, turpis quis ultrices suscipit, mi turpis vehicula augue, vitae dictum nisl turpis a purus. Ut sagittis metus ipsum, sit amet malesuada leo pharetra nec. Sed ultrices luctus venenatis. Vivamus et luctus tortor, id auctor massa. Suspendisse potenti.</p>
            <p>Curabitur nisi nibh, porttitor vel feugiat vel, pulvinar non neque. Suspendisse dignissim, mi a posuere varius, neque tellus dapibus nunc, eu consectetur orci risus eu dui. Donec id vulputate dolor, non faucibus eros. Nullam nulla dui, ultricies id purus ac, rhoncus iaculis lacus. Curabitur eget purus consectetur augue mattis commodo facilisis sit amet lorem. Etiam luctus non diam non mollis. Phasellus ac lectus vitae arcu tincidunt volutpat at vitae magna. Nam facilisis tempor lacus convallis mollis. In eleifend placerat commodo. Vestibulum nulla enim, facilisis ut quam sit amet, varius ultrices urna. Sed blandit ligula quis condimentum accumsan.</p>
            <p>Maecenas sit amet turpis sem. Pellentesque magna nulla, sodales quis aliquet sit amet, consectetur non lacus. Integer porttitor tincidunt nisl, at placerat leo malesuada eget. Pellentesque interdum tristique eros, id dictum eros consectetur pulvinar. Praesent sit amet justo vel dui fermentum lacinia. Maecenas sapien metus, porttitor sed feugiat congue, posuere et ipsum. Mauris id gravida tellus, eget placerat dolor. Nullam sed massa in quam maximus finibus.<p>
            <p>Quisque non magna quis ex convallis commodo. Maecenas pulvinar urna nisl, a consectetur tortor convallis non. Maecenas sodales nunc et augue fermentum sollicitudin. Aliquam quis nisi neque. Quisque dignissim urna sed sodales vestibulum. Nullam ac lectus elit. Sed condimentum feugiat varius. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc eleifend molestie magna id tempus.</p>
            <p>Ut dapibus risus at arcu tempor accumsan. Duis faucibus turpis vel eleifend porttitor. Phasellus vehicula condimentum felis, blandit egestas nisi lacinia id. Aenean tempus augue a quam vulputate, vitae egestas sapien sodales. Sed eget ultrices massa. Sed aliquet eros erat, tincidunt mattis neque ultricies in. Phasellus vitae nunc luctus, pulvinar ligula et, finibus turpis. Cras sit amet turpis eget arcu vestibulum fermentum a quis lectus. Proin ultricies turpis fermentum, accumsan justo vel, efficitur nisl. Curabitur vel libero justo. Vestibulum magna felis, semper nec nisl nec, tempus eleifend leo. Vivamus venenatis libero sapien. Vivamus blandit efficitur nunc nec iaculis. Nam ipsum ipsum, sagittis vel odio sed, interdum tempus eros. Suspendisse potenti.</p>
            <p>Etiam suscipit nisi eget ante venenatis, in laoreet libero placerat. Curabitur molestie, tortor ut venenatis venenatis, neque neque pellentesque purus, vitae sagittis purus erat sit amet ante. Sed sed mattis sapien. Etiam ac aliquet nisi, id pulvinar neque. Phasellus lacinia, lorem eget pretium sodales, est nibh semper libero, id vestibulum mi ex id leo. Pellentesque ac felis augue. Maecenas accumsan eros est, quis hendrerit elit pellentesque vel. Phasellus vel neque elit. Proin dignissim ligula nunc, non convallis diam fringilla ac. Fusce diam enim, pellentesque at semper eget, posuere vitae tellus. Cras ac nulla in risus fringilla rutrum id at sapien. In bibendum viverra ante, ut condimentum ligula hendrerit eget. Suspendisse accumsan justo ac dignissim interdum.</p>
            </v-row>
    </v-container>
</template>
