<template>
    <v-container>
        <v-row justify="center" class="mx-15">
            <h1 class="display-2 font-weight-bold mb-3">Expension's terms of agreement</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce dapibus sapien vel rhoncus vehicula. Sed semper odio sed risus fermentum, non fringilla magna fermentum. Duis pellentesque ex faucibus ex varius, ac tristique enim feugiat. Sed non malesuada metus, eu sollicitudin nisl. Vivamus at ultrices eros, at pretium quam. Donec rutrum faucibus ipsum, a maximus tortor rutrum vitae. Nullam massa felis, lacinia eget ullamcorper quis, faucibus nec urna. Aenean vel viverra dui, id pellentesque erat. Aenean nec aliquam erat. Mauris et tortor vitae tellus rhoncus tristique nec id diam. Duis laoreet et odio et posuere. Praesent rutrum a tortor ullamcorper maximus.</p>
            <p>Proin rutrum risus nunc, sed tristique diam luctus at. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam iaculis dui congue tempus pretium. Sed ultrices augue quis varius auctor. Nam efficitur ex sed sodales cursus. Integer quis mi auctor, imperdiet nisl ac, auctor enim. Ut tellus urna, ornare bibendum posuere eu, scelerisque quis lacus. Donec efficitur placerat sapien in tristique. Sed hendrerit consequat lorem quis placerat. Nullam quis arcu sit amet odio pharetra porttitor non quis lacus. Morbi dui metus, vulputate et scelerisque ut, porttitor sit amet dui. In hac habitasse platea dictumst. In ornare sapien leo. Fusce eget porttitor purus, a malesuada metus. Nunc condimentum lectus nisi, at tristique nibh imperdiet non.</p>
            <p>Donec pretium, dui in placerat mattis, ligula leo finibus ante, in scelerisque nunc ex nec quam. Ut sit amet pretium nibh, ut lacinia nisi. Proin pellentesque mollis urna, a maximus erat consequat et. Aenean pretium dapibus lorem, a pharetra purus cursus eget. Nullam vulputate ut arcu id euismod. Donec interdum tellus sit amet mauris eleifend bibendum. Etiam eros felis, varius id accumsan sit amet, feugiat non nisl. Nam auctor vestibulum lacus sit amet tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec cursus placerat venenatis.</p>
            <p>Cras at egestas nisi. Fusce pellentesque, enim non vehicula commodo, eros tellus finibus neque, maximus aliquet lorem nunc nec orci. Vivamus sollicitudin odio nulla, non ullamcorper nibh ornare ac. Sed elementum nisl ut dui viverra laoreet. Donec sed porta lectus. Morbi ante eros, iaculis at aliquam eget, dictum sagittis eros. Morbi ac lobortis felis. Sed eu metus ac nunc pharetra vestibulum ac sit amet tellus. Maecenas tempus elit nec feugiat auctor. Integer elementum eget justo in vestibulum.</p>
            <p>Nunc eget augue vitae sem volutpat ornare eget ac arcu. Maecenas nec elit sed tellus congue maximus ac ut sapien. Pellentesque posuere velit nec cursus malesuada. Duis vulputate laoreet nisi sit amet laoreet. Sed gravida nisl tortor, non maximus felis blandit a. Curabitur ligula risus, eleifend eu felis vel, congue dapibus mauris. Fusce tincidunt risus ut erat malesuada, ac luctus felis aliquam. Suspendisse turpis dolor, volutpat sit amet nisi non, porta bibendum magna. Duis neque dui, hendrerit blandit massa eu, dictum porta neque. Nulla quis ultricies dui. Cras iaculis nulla ac ante pharetra, vitae finibus nisi ullamcorper. Donec scelerisque elit in urna ullamcorper iaculis. Nulla volutpat tellus sed pellentesque bibendum. Aliquam dictum pulvinar risus, ut cursus enim suscipit ut. Sed at malesuada augue. Vivamus eget luctus nunc.</p>
            <p>Proin sit amet mi eu quam convallis efficitur. Phasellus semper enim eu nibh placerat porta et vitae sem. Sed euismod risus a lorem viverra, vel fringilla augue vulputate. Praesent ornare molestie massa ut condimentum. Aliquam pulvinar interdum blandit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean elit tellus, cursus quis tempor non, tempus a dui. Donec sed scelerisque dui. Nam gravida diam vitae blandit consequat. Donec accumsan, magna eget egestas rhoncus, lectus risus hendrerit justo, a iaculis nisl sem pulvinar urna. Nunc at orci lobortis metus condimentum ullamcorper eget et est.</p>
            <p>Curabitur diam lorem, tincidunt ut ullamcorper nec, mollis sit amet quam. Nulla elementum nisi non purus auctor, ac sollicitudin mi tristique. Etiam condimentum sem sit amet tempor vulputate. Sed maximus nibh id libero condimentum, ut feugiat lorem venenatis. Ut tristique elit non massa rutrum scelerisque. Sed eget tempor est. Vivamus scelerisque leo in est pretium, sollicitudin condimentum elit fringilla. Vestibulum nisl enim, ullamcorper id feugiat sed, iaculis vel ante. Cras aliquet nisi eget dolor aliquam, vel porta risus scelerisque. Donec molestie leo vitae sollicitudin imperdiet. Curabitur nec mi nec tortor auctor posuere. Vivamus in erat ut magna maximus vestibulum. Nulla facilisi. Maecenas et lectus massa.</p>
            <p>Etiam rutrum, lacus id tincidunt commodo, enim purus ornare sapien, a convallis risus lacus ac purus. Vivamus accumsan dolor ut erat imperdiet, congue eleifend neque gravida. Morbi ultricies libero vel lectus fermentum, a aliquam tellus condimentum. Donec consectetur ex blandit, venenatis quam ut, rutrum nunc. Donec convallis massa non enim laoreet, pulvinar feugiat ex iaculis. Vestibulum augue tellus, pharetra a arcu vel, posuere congue risus. Fusce tortor lorem, finibus a interdum luctus, fermentum sit amet est. Nam interdum neque non ullamcorper fringilla. Mauris a tortor justo. Proin bibendum non neque non euismod. Vestibulum vel condimentum lacus. Suspendisse efficitur justo nulla, sed convallis risus auctor a. Vestibulum dignissim nisl eu tortor viverra pellentesque. Ut malesuada molestie mi sit amet dignissim. Vivamus libero dolor, lobortis at iaculis sed, tempus vel ipsum.</p>
            <p>Duis nec sem tincidunt, bibendum nulla et, maximus risus. Mauris eget diam velit. Donec nec tempus ex. Vivamus sed urna eu turpis pellentesque vulputate a vitae nibh. Aenean ac ligula pretium, tincidunt ligula quis, posuere odio. Vivamus at metus neque. Cras fringilla ullamcorper mauris, et tristique est vehicula et.</p>
            <p>Nunc eu mauris diam. Fusce a vestibulum nisi, vitae suscipit arcu. Proin id ipsum dignissim, molestie est luctus, dictum elit. Ut ac venenatis mauris. Suspendisse euismod, nisl id malesuada convallis, quam purus lacinia diam, quis elementum sem justo id ante. Integer vel diam vehicula, condimentum leo sed, interdum mi. Nulla gravida blandit dolor, vestibulum viverra tortor dictum quis. Curabitur porttitor tempor risus. Phasellus posuere iaculis leo at laoreet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
        </v-row>
    </v-container>
</template>
